[build]
base = "random-acts/"
publish = "random-acts/build/"
command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  from = '/api/*'
  to = "https://random-acts-webpt5.herokuapp.com/:splat"
  status = 200
